template_path: cloudfront.yaml.j2

project_code: cloudfront

stack_name: enaia-cloudfront-dev

parameters:
  Env                            : "dev"
  S3BucketNamePrivateContent     : "enaia-dev-s3-private-content"
  S3BucketPathPrivateContent     : "/path1/*" # Path in cloudfront to route to this origin
  S3BucketNameImages             : "enaia-dev-s3-images"
  S3BucketPathImages             : "/path2/*" # Path in cloudfront to route to this origin
  CustomOriginName               : "www.customorigin.com" # This will be the default one in Cloudfront
  CloudfrontAlias                : "assets.enaia.co"
  CFViewerCertificateARN         : "arn:aws:acm:us-east-1:020275857710:certificate/c48210c0-8550-4d93-a849-b6ab28eec5a9"