#!/usr/bin/python

# After running the script which create database ProiectBD2
# and the tables needed, we need to populate those tables

import MySQLdb

# Open database connection 
db = MySQLdb.connect("localhost","root","mysqlpass")

# Prepare a cursor object using cursor() method
cursor = db.cursor()

# Use the database ProiectBD2
cursor.execute("USE ProiectBD2")

# For table coduriPiese

cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('AZK5563')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('RDS4363')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('TRS4643')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('ARM4345')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('RDT5522')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('MMM6655')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('TTR5338')")
cursor.execute("INSERT INTO coduriPiese (codPiesa) VALUES ('PPC4412')")

# For table motoare

cursor.execute("""INSERT INTO motoare (codMotor, codFiltruPolen, codFiltruCombustibil, codFiltruAer, codFiltruUlei)
					VALUES ('D4F-F7', 'AZK5563', 'TRS4643', 'RDT5522', 'TTR5338')""")
cursor.execute("""INSERT INTO motoare (codMotor, codFiltruPolen, codFiltruCombustibil, codFiltruAer, codFiltruUlei)
					VALUES ('K7J-A7', 'AZK5563', 'TRS4643', 'MMM6655', 'PPC4412')""")
cursor.execute("""INSERT INTO motoare (codMotor, codFiltruPolen, codFiltruCombustibil, codFiltruAer, codFiltruUlei)
					VALUES ('K7M710', 'AZK5563', 'ARM4345', 'MMM6655', 'TTR5338')""")
cursor.execute("""INSERT INTO motoare (codMotor, codFiltruPolen, codFiltruCombustibil, codFiltruAer, codFiltruUlei)
					VALUES ('K9K-K7', 'RDS4363', 'TRS4643', 'RDT5522', 'PPC4412')""")

# For table masini
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Logan', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Logan', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Logan', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Logan', 'motorina', 1500, 'K9K-K7')""")					
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Sandero', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Sandero', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Sandero', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Sandero', 'motorina', 1500, 'K9K-K7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Duster', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Duster', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Duster', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Duster', 'motorina', 1500, 'K9K-K7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Lodgy', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Lodgy', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Lodgy', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Lodgy', 'motorina', 1500, 'K9K-K7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Dokker', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Dokker', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Dokker', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Dokker', 'motorina', 1500, 'K9K-K7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Pick-up', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Pick-up', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Pick-up', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'Pick-up', 'motorina', 1500, 'K9K-K7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'MCV', 'benzina', 1200, 'D4F-F7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'MCV', 'benzina', 1400, 'K7J-A7')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'MCV', 'benzina', 1600, 'K7M710')""")
cursor.execute("""INSERT INTO masini (marcaMasina, modelMasina, combustibil, capacitate, codMotor)
					VALUES ('Dacia', 'MCV', 'motorina', 1500, 'K9K-K7')""")

#We have the following codes: 'AZK5563' 'RDS4363'   'TRS4643' 'ARM4345'   'RDT5522' 'MMM6655'   'TTR5338' 'PPC4412'

# For table piese

cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (342, 'Bosch', 'Filtru Polen', 'AZK5563', 25)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (343, 'Starline', 'Filtru Polen', 'AZK5563', 13)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (344, 'Dacia', 'Filtru Polen', 'AZK5563', 55)""")

cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (356, 'Bearmach', 'Filtru Polen', 'RDS4363', 21)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (357, 'Bosch', 'Filtru Polen', 'RDS4363', 11)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (358, 'Dacia', 'Filtru Polen', 'RDS4363', 70)""")



cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (401, 'Bearmach', 'Filtru Combustibil', 'TRS4643', 15)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (402, 'Starline', 'Filtru Combustibil', 'TRS4643', 21)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (403, 'Dacia', 'Filtru Combustibil', 'TRS4643', 100)""")

cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (441, 'Bosch', 'Filtru Combustibil', 'ARM4345', 20)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (442, 'Starline', 'Filtru Combustibil', 'ARM4345', 34)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (443, 'Dacia', 'Filtru Combustibil', 'ARM4345', 56)""")



cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (651, 'Bearmach', 'Filtru Aer', 'RDT5522', 30)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (652, 'Starline', 'Filtru Aer', 'RDT5522', 41)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (653, 'Dacia', 'Filtru Aer', 'RDT5522', 55)""")

cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (661, 'Bosch', 'Filtru Aer', 'MMM6655', 46)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (662, 'TRW', 'Filtru Aer', 'MMM6655', 33)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (663, 'Dacia', 'Filtru Aer', 'MMM6655', 120)""")



cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (751, 'TRW', 'Filtru Ulei', 'TTR5338', 19)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (752, 'Starline', 'Filtru Ulei', 'TTR5338', 22)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (753, 'Dacia', 'Filtru Ulei', 'TTR5338', 34)""")

cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (781, 'Bearmach', 'Filtru Ulei', 'PPC4412', 24)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (782, 'TRW', 'Filtru Ulei', 'PPC4412', 32)""")
cursor.execute("""INSERT INTO piese (IDPiesa, producator, numePiesa, codPiesa, pretPiesa)
					VALUES (783, 'Bosch', 'Filtru Ulei', 'PPC4412', 99)""")


# For table magazine

cursor.execute("""INSERT INTO magazine (IDMagazin, numeMagazin, adresaMagazin)
					VALUES (10, 'AlexPieseShop SRL', 'Str Mecanicii, nr 2-4, Sector 1')""")
cursor.execute("""INSERT INTO magazine (IDMagazin, numeMagazin, adresaMagazin)
					VALUES (20, 'AutoDoctor SRL', 'Str Marie-Curie, nr 45, Sector 2')""")
cursor.execute("""INSERT INTO magazine (IDMagazin, numeMagazin, adresaMagazin)
					VALUES (30, 'PieseAutoMagazin SRL', 'Str Izvorul de foc, nr 1, Sector 3')""")
cursor.execute("""INSERT INTO magazine (IDMagazin, numeMagazin, adresaMagazin)
					VALUES (40, 'AjutorPiese SRL', 'Str Razboiului, nr 66, Sector 4')""")
cursor.execute("""INSERT INTO magazine (IDMagazin, numeMagazin, adresaMagazin)
					VALUES (50, 'AutoBaza SRL', 'Str Maior Patitu, nr 10, Sector 5')""")
cursor.execute("""INSERT INTO magazine (IDMagazin, numeMagazin, adresaMagazin)
					VALUES (60, 'MasinaCare SRL', 'Str Stefan cel Mircea, nr 77, Sector 6')""")


# For table stocuri

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (342, 10, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (342, 20, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (342, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (342, 50, 1)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (343, 10, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (343, 40, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (343, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (343, 60, 1)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (344, 40, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (344, 20, 4)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (344, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (344, 50, 2)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (356, 60, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (356, 40, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (356, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (356, 50, 3)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (357, 10, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (357, 40, 1)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (358, 10, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (358, 20, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (358, 30, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (358, 50, 1)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (401, 10, 7)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (401, 20, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (401, 30, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (401, 50, 2)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (402, 40, 20)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (402, 60, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (402, 30, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (402, 50, 2)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (403, 40, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (403, 20, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (403, 60, 4)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (403, 50, 1)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (441, 10, 9)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (441, 40, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (441, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (441, 60, 6)""")


cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (442, 50, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (442, 40, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (442, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (442, 60, 8)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (443, 10, 4)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (443, 20, 4)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (443, 30, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (443, 40, 1)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (651, 40, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (651, 20, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (651, 30, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (651, 10, 4)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (652, 40, 11)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (652, 20, 22)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (652, 30, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (652, 10, 8)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (653, 40, 11)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (653, 20, 10)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (653, 50, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (653, 10, 3)""")


cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (661, 40, 11)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (661, 20, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (661, 30, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (661, 10, 4)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (662, 40, 13)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (662, 60, 10)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (662, 30, 9)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (662, 50, 11)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (663, 60, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (663, 20, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (663, 50, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (663, 10, 5)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (751, 10, 10)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (751, 20, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (751, 30, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (751, 40, 10)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (752, 60, 9)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (752, 20, 7)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (752, 30, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (752, 50, 10)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (753, 10, 10)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (753, 20, 5)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (753, 50, 6)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (753, 40, 4)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (781, 50, 10)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (781, 20, 3)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (781, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (781, 40, 5)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (782, 50, 4)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (782, 20, 6)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (782, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (782, 10, 7)""")

cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (783, 50, 10)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (783, 30, 1)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (783, 30, 2)""")
cursor.execute("""INSERT INTO stocuri (IDPiesa, IDMagazin, cantitateMagazin)
					VALUES (783, 10, 2)""")

# commit changes
db.commit()

# disconnect from server
db.close()